### ISSUE TITLE
Peer Review [Group 95]

### ISSUE THREAD

**Issue by Marziazaidi** [leoyliu/Forecasting-the-2024-US-Presidential-Election#6]
The paper by Yuanyi Liu, Dezhen Chen, and Ziyuan Shen presents a model-based forecast for the 2024 U.S. presidential election, focusing on Kamala Harris' candidacy. Using logistic regression and a poll-of-polls approach, it aims to smooth out fluctuations in voter sentiment across multiple polls, thereby improving prediction reliability.

Strong Positive Points:

- The paper outlines the logistic regression model clearly, making the technical approach easy to follow.
- R is cited and the repo has no indication that it is a class paper.
- The link to the GitHub repo is provided in the paper.
- The authors ensure that only high-quality polls are used, which increases the reliability of the results.
- The variables are defined in the Measurement section effectively.

Critical Improvements Needed:

- Sketches are not updated.
- LLM chat is not provided whereas in the ReadMe section it says that it was used.
- Remove unnecessary files or folders from the repo.
- Graphs/Tables are missing 
- The result and discussion sections are missing.
- Appendix section has to be updated and unnecessary graphs and data should be removed.
- The structure lacks clarity in several sections, such as the discussion, which could better summarize the findings and their implications. The section headers like “First discussion point” should be replaced with meaningful titles.
- Some references are missing or incomplete (e.g., the text references certain figures like “?@fig-stan” which are not included). The final version should ensure that all references and cross-references are correct.

Suggestions for Improvement:

- Correct the references section and include missing references.
- The repository has many excess files that makes it hard to go through everything. Make sure that you remove them.
- Include graphs or tables summarizing key findings, such as voter preference over time or model accuracy metrics.
- The appendix needs to be properly formatted, particularly for including any supplementary details on the model.
- Add the LLM usage and sketches.

Evaluation:

1. 【R appropriately cited: 1/1】 - R is cited properly
2. 【Data appropriated cited: 1/1】-The Data is properly cited
3. 【Class paper: 1/1】-There’s no sign that it is a class project.
4. 【LLM usage documented: 0/1】- LLM usage is NOT documented in  llm.usage.txt
5. 【Title: 1/2】- Subtitle could be improved.
6. 【Author, data and repo: 2/2】- All three elements are provided.
7. 【Abstract: 3/4】- 
8. 【Introduction:2/4】- Need more context of "what was found" in the analysis. Make it concise.
9. 【Estimand: 0/1】- Not mentioned.
10. 【Data: 6/10】- Could be improved
11. 【Measurement: 4/4】- Measurements are clearly described.
12. 【Model: 0/10】-Incomplete
13. 【Results: 0/10】- Incomplete
14. 【Discussion: 0/10】- Incomplete
15. 【Prose: 4/6】
16. 【Cross-references: 1/1】
17. 【Captions: 1/2】-Could be improved.
18. 【Graphs/tables/etc: 1/4】-More visuals need to be present to display results.
19. 【Idealized methodology: 0/10】
20. 【Idealized survey: 0/4】
21. 【Pollster methodology overview and evaluation: 0/10】
22. 【Referencing: 2/4】- Few Mistakes.
23. 【Commits: 2/2】- Meaningful commits.
24. 【Sketches: 0/2】- Not included.
25. 【Simulation: 4/4】
26. 【Tests-simulation: 0/4】- Not included
27. 【Tests-actual: 0/4】- Not included
28. 【Parquet: 0/1】
29. 【Reproducibility: 2/4】-More data needed to ensure reproducibility.
30. 【Miscellaneous: 2/3】

Estimated overall mark:
40/126

**Comment by Serena-SHEN1011** [comment]
Thank you for the thorough review and helpful suggestions. We appreciate the specific points you've provided on areas for improvement, such as adding missing references, including more visuals, and ensuring LLM usage is documented properly. We'll work on these to improve the clarity and completeness of the paper.
