### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [leoyliu/Forecasting-the-2024-US-Presidential-Election#7]
- R is appropriately cited (1/1)
	- Fine.
- Data are appropriately cited (0/1)
	- "(Ryan Best)" - I'm guessing that's wrong and it's meant to be Best.
- Class paper (1/1)
	- Fine.
- LLM usage is documented (1/1)
	- Fine.
- Title (1/2)
	- Title is great.
	- Subtitle needs to tell me what your main finding is.
- Author, date, and repo (2/2)
	- Fine.
- Abstract (0/4)
	- 239 + 98 does not equal 538. So I don't understand your electoral college numbers here.
	- After you fix the that electoral college issue this is fine and would be 3/4.
- Introduction (2/4)
	- Same comment as in abstract.
	- There should be uncertainty around your estimates right?
- Estimand (1/1)
	- Don't have a separate estimand subsection, just move that paragraph into the introduction before the telegraphing paragraph.
- Data (8/10)
	- Good start. 
- Measurement (3/4)
	- Good start. 
- Model (8/10)
	- Good start. 
- Results (8/10)
	- Good start. 
- Discussion (7/10)
	- Good start.
- Prose (4/6)
	- Be concise. Remove unnecessary words.
- Cross-references (1/1)
	- Fine
- Captions (2/2)
	- Nice.
- Graphs/tables/etc (2/4)
	- Add alpha to Figure 1
- Idealized methodology (7/10)
	- Good start. 
- Idealized survey (3/4)
	- Good start. 
- Pollster methodology overview and evaluation (8/10)
	- What is L2?
	- Good start.
- Referencing (0/4)
	- As mentioned "Ryan Best" is probably wrong and should porbably be "Best, Ryan"
	- Capitalization of R packages is wrong e.g. Dplyr. See the piazza comment about this.
- Commits (2/2)
	- Fine
- Sketches (1/2)
	- Fine
- Simulation (3/4)
	- Good start.
	- Add some sophistication to this
- Tests-simulation (3/4)
	- Good start.
	- Why are these if/else while the actual tests are testthat?
- Tests-actual (3/4)
	- Good start.
- Parquet (1/1)
	- Fine.
- Reproducible workflow (2/4)
	- Okay.
	- Don't forget to comment and close all issues.
- Miscellaneous (1/3)
	- Nice use of install packages script.

**Comment by leoyliu** [comment]
Thank you for the feedback. We’ve corrected the citation format, adjusted the electoral college numbers in the abstract and introduction, and moved the estimand paragraph to the introduction. We’ll refine the prose for conciseness and add alpha to Figure 1. Closing this issue as we make these updates.
