### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RohanAlexander** [leoyliu/Forecasting-the-2024-US-Presidential-Election#8]
- Can you consider using a `modelsummary` table instead of Table 3. It's a better option for model results tables rather than DIY. If you have too many variables then consider putting it into an appendix and cross-referencing it and/or using a `modelsummary` plot.

Feel free to make this change if you want. Marking is done.

**Comment by leoyliu** [comment]
Thank you for the feedback! I actually did include the full summary table in the appendix, where I used a `modelsummary` table and ensured it was cross-referenced within the main text.

By the way, I’m curious—aside from this minor issue, how was the overall marking of our paper?

**Comment by RohanAlexander** [comment]
Oh, I missed that, sorry. Thanks for pointing that out. I have marked everything and now the TAs will go through and check everything. I had you on 124/126, but that might shift slightly depending on what they say.

May I use the paper as an example please?

**Comment by leoyliu** [comment]
Thank you for the feedback and for considering it in such detail! I appreciate the high score, and I understand if it shifts a bit after the TAs review. I'd be honored to have the paper used as an example—please feel free to do so!

**Comment by RohanAlexander** [comment]
Okay. Thank you very much.
